project_id = "xamkaphelshsavcacbdy"

[functions.chat-ai-assistant]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.profile]
timeout_ms = 30000

# Add public (default) access for math-tutor-assistant
[functions.math-tutor-assistant]
verify_jwt = false
