export interface Definition {
  term: string;
  definition: string;
  source?: string;
}

export interface GlossaryItem {
  term: string;
  definition: string;
}

export interface Reference {
  theme: string;
  refs: string[];
}

export interface HookExample {
  subject: string;
  hook: string;
  type: string;
}

export const DEFINITIONS: Definition[] = [
  { term: 'Mondialisation', definition: "Processus historique d'extension progressive du systeme capitaliste dans l'espace geographique et d'intensification des echanges et des flux a l'echelle mondiale qui debouche sur la creation d'un espace mondial de plus en plus integre.", source: 'Laurent Carroue, Geographie de la mondialisation; Pascal Gauchon, Dictionnaire de geopolitique et de geoeconomie' },
  { term: 'Developpement', definition: "Combinaison des changements mentaux et sociaux d'une population qui la rendent apte a faire croitre cumulativement et durablement son produit reel global; approche par les capabilites: capacite a convertir les ressources en libertes reelles.", source: 'Francois Perroux; Amartya Sen' },
  { term: 'Emergence', definition: "Passage de l'ombre a la lumiere: sortie du sous-developpement et possible acces a la puissance (economique d'abord, mais aussi politique, culturelle, militaire) caracterise par une croissance forte et soutenue de long terme.", source: 'Sylvia Delannoy, Dictionnaire de geopolitique et de geoeconomie' },
  { term: 'Puissance', definition: "Capacite de faire, de faire faire, d'empecher de faire, ou de refuser de faire: faculte d'inflechir les comportements d'autres acteurs dans le systeme international.", source: 'Serge Sur, Les Relations internationales' },
  { term: 'Guerre', definition: "Acte de violence destine a contraindre l'adversaire a executer notre volonte; lutte armee s'inscrivant dans la duree et poursuivant un but politique.", source: 'Raymond Aron' },
  { term: 'Energie', definition: "Grandeur physique (joule) mesurant la capacite d'un systeme a produire un travail. Chaine de valeur: exploration, exploitation, acheminement, commercialisation, consommation. Sources: fossiles, nucleaire, renouvelables." },
  { term: 'Ressources', definition: "Ensemble des elements biotiques et abiotiques de la Terre constituant les moyens materiels dont dispose une entite (pays, region, collectivite); a distinguer des matieres premieres." },
  { term: 'Territoire', definition: "Espace concu, mis en valeur et organise par une communaute; support de representations, de pouvoirs et de projets collectifs.", source: 'Pascal Gauchon, Dictionnaire de geopolitique et de geoeconomie' },
  { term: 'Etat', definition: "Organisation politique exercant le monopole de la violence physique legitime sur un territoire donne et dotee d'institutions edictant le droit; fonctions regaliennes: securite, impot, monnaie, diplomatie.", source: 'Max Weber, Le savant et le politique' },
  { term: 'Nation', definition: "Communaute politique fondee sur un desir de vivre ensemble et la volonte de poursuivre un heritage commun sur un territoire donne, personnifiee par une autorite souveraine.", source: 'Ernest Renan, Qu est-ce qu une nation?' },
  { term: 'Colonisation', definition: "Conquete et mise sous domination politique et economique d'un territoire ou d'un Etat par un autre.", source: 'Frederic Pichon, Dictionnaire de geopolitique et de geoeconomie' },
  { term: 'Empire', definition: "Forme de domination exercant un controle sur des populations, des territoires, des ressources et des flux au-dela des frontieres nationales de la puissance imperiale." },
  { term: 'Conflit / Conflictualite', definition: "Ensemble des etats intermediaires entre la paix parfaite et la guerre totale; tensions pouvant evoluer vers la crise ou l'affrontement arme.", source: 'Geoconfluences' },
  { term: 'Terrorisme', definition: "Methode d'action violente repetee, destinee a inspirer l'inquietude, employee par des groupes clandestins ou des Etats; les cibles directes ne sont pas les cibles principales.", source: 'Alex P. Schmid (typologie academique)' },
  { term: 'Clivage', definition: "Separation de groupes selon des criteres (sociaux, territoriaux, ideologiques) produisant des lignes de fracture structurantes." },
  { term: 'Crise', definition: "Moment de bouleversement multiforme rompant un equilibre et conduisant au passage d'une phase stable (ou de croissance) a une phase de recession ou de reconfiguration." },
  { term: 'Ordre mondial', definition: "Configuration hierarchisee des puissances et regles de fonctionnement des relations internationales a une periode donnee." },
  { term: 'Frontiere', definition: "Structure spatiale lineaire marquant une discontinuite geopolitique et jouant des fonctions de repere, de marquage et d'interface (effet-barriere / effet-passerelle).", source: 'Michel Foucher, Fronts et frontieres' },
  { term: 'Geopolitique', definition: "Etude des rivalites de pouvoir et d'influence sur des territoires et les populations qui y vivent, impliquant Etats et acteurs non etatiques.", source: 'Yves Lacoste' },
  { term: 'Geoeconomie', definition: "Analyse des strategies economiques conduites par les Etats pour defendre leurs interets dans un contexte ou les antagonismes s'expriment par l'affrontement economique.", source: 'Edward Luttwak (annees 1990)' },
  { term: 'Defis', definition: "Incitations a realiser une action difficile; obstacles a franchir pour atteindre un objectif dans un contexte donne." },
  { term: 'Enjeux', definition: "Ce que l'on peut gagner ou perdre dans une entreprise; se declinent par typologies, acteurs concernes, echelles et consequences." },
  { term: 'Influence', definition: "Capacite de persuasion et d'attraction (soft power) s'exercant par le soutien diplomatique, les alliances, l'aide au developpement, l'exportation d'un modele." },
  { term: 'Ingerence', definition: "Interventions directes, civiles ou militaires, visant a exercer un pouvoir de forte intensite sur un autre Etat (coercition / hard power)." },
  { term: 'Relations internationales', definition: "Ensemble des liens, rapports et contacts s'etablissant entre Etats et relevant de leur politique etrangere." },
  { term: 'Religion', definition: "Systeme de croyances, dogmes et rites structurant le rapport au sacre; facteur de cohesion ou de legitimation pour certains acteurs." },
  { term: 'Tension', definition: "Situation de desaccord ou d'equilibre precaire entre acteurs pouvant entrainer risques de conflit, crise ou rupture." },
  { term: 'Rivalite', definition: "Competition entre acteurs pour les memes avantages; notion centrale en geopolitique." },
  { term: 'Cooperation', definition: "Action de participer ensemble a une oeuvre commune en vue d'un but specifique, selon des interets partages (partenariat)." },
  { term: 'Defense', definition: "Ensemble des moyens (notamment militaires) destines a proteger l'integrite territoriale et la securite des populations." },
  { term: 'Securite', definition: "Situation objective d'absence de danger ou de menace pour les personnes et les biens, fondee sur des conditions materielles, politiques et sociales." },
  { term: 'Fragmentation', definition: "Processus de division de ce qui etait uni ou homogene, a toutes les echelles et dans divers espaces.", source: 'S. Rosiere, Geographie politique et geopolitique' },
  { term: 'Integration', definition: "Renforcement des liens unissant les elements d'un systeme (politico-institutionnel, economique, territorial), via politiques de convergence et institutions.", source: 'Bernard Bret' },
  { term: 'Mutation', definition: "Changement economique et social radical modifiant en profondeur les structures d'un systeme." },
  { term: 'Gouvernance mondiale', definition: "Cadre institutionnel multilateral associant divers acteurs et fixant des regles et normes reconnues; debat sur le role d'un hegemon pour la stabilite.", source: 'Charles Kindleberger (theorie de la stabilite hegemonique)' },
];

export const GLOSSARY: GlossaryItem[] = [
  { term: 'Gendarmes du monde', definition: "Terme lie a l'hyperpuissance: apres la guerre froide, les USA dominent tous les domaines (hegemon) et endossent la charge de l'ordre mondial." },
  { term: 'Desindustrialisation', definition: "Diminution de la part de l'industrie dans le PIB et l'emploi." },
  { term: 'Ordre', definition: "Par opposition au desordre; suppose une stabilite et des regles partagees." },
  { term: 'Mobilites', definition: "Ensemble des deplacements temporaires lies au travail." },
  { term: 'Migration', definition: "Changement de residence impliquant un deplacement durable." },
  { term: 'Bidonville', definition: "Habitat precaire sans services urbains associes et sans titre de propriete." },
  { term: 'Balkanisation', definition: "Processus de division d'un ensemble territorial/politique en entites plus petites, souvent en conflit." },
  { term: 'Dividende demographique', definition: "Phase de transition demographique ou les actifs sont nombreux, la natalite faible et la population agee limitee - favorable a la croissance." },
  { term: 'Quart monde', definition: "Population des pays developpes vivant sous le seuil de pauvrete." },
  { term: 'Revolution verte', definition: "Politiques agricoles visant a accroitre la productivite pour atteindre l'autosuffisance." },
  { term: 'Sous-developpement', definition: "Situation des PMA marquee par pauvrete de masse, fortes inegalites, insecurite alimentaire/sanitaire (Sylvie Brunel)." },
  { term: 'Diplomatie', definition: "Art de representer un Etat aupres d'un autre pour regler les differends sans recourir a la force." },
  { term: 'Superpuissance', definition: "Nation au rayonnement economique, culturel, politique et militaire preeminent. Pendant la GF: USA et URSS." },
  { term: 'Hyperpuissance', definition: "Vedrine: domination globale des Etats-Unis apres la GF, incluant un puissant soft power." },
  { term: 'Hegemonie', definition: "Suprematie permettant de diriger les affaires; une seule puissance veritablement hegemonique a la fois." },
  { term: 'Leadership', definition: "Preeminence et initiative revendiquees; domination volontaire, non imposee." },
  { term: 'Imperialisme', definition: "Politique d'un Etat visant a placer d'autres sous dependance politique/economique." },
  { term: 'Islamisme', definition: "Ideologie politique pronant un Etat fonde sur l'islam." },
  { term: 'Soft power (Joseph Nye)', definition: "Capacite d'influence par la persuasion (entreprises, culture, individus) plutot que par la force." },
  { term: 'DIT / NDIT', definition: "Specialisations fondees sur les avantages comparatifs; la NDIT traduit l'industrialisation au Sud (vol d'oies sauvages, Akamatsu)." },
  { term: 'DIPP / Chaines de valeur', definition: "Division internationale des processus de production: modularisation, sous-traitance et circulation de composants." },
  { term: 'Dragons asiatiques', definition: "Coree du Sud, Taiwan, Hong Kong, Singapour - trajectoires d'industrialisation rapide." },
  { term: 'Droit d asile', definition: "DUDH 1948, art. 14: toute personne persecutee a le droit de chercher et de beneficier de l'asile." },
  { term: 'Hard power', definition: "Pouvoir de contrainte/coercition d'un Etat." },
  { term: 'Economie collaborative', definition: "Echanges de biens/services entre particuliers via plateformes (ex. BlaBlaCar)." },
  { term: 'Economie informelle', definition: "Activites remuneratrices hors controle de l'Etat." },
  { term: 'Risque', definition: "Capacite sans volonte: potentiel de nuisance non actualise." },
  { term: 'Menace', definition: "Capacite + volonte: danger actualise." },
  { term: 'Empreinte ecologique', definition: "Surface necessaire pour produire et absorber les rejets d'une population." },
  { term: 'Guerre (Sun Tzu)', definition: "Art de soumettre l'ennemi sans combattre." },
  { term: 'Fin de l histoire (F. Fukuyama, 1992)', definition: "These d'un triomphe planetaire de la democratie liberale apres la GF (controversee)." },
  { term: 'Financiarisation de l economie', definition: "Montee du poids des activites financieres dans le PIB via dereglementation et innovation financiere." },
  { term: 'Syndrome hollandais', definition: "Lien entre exploitation de ressources et declin manufacturier/competitivite." },
  { term: 'Smart power', definition: "Combinaison intelligente du hard et du soft power (Obama, Clinton)." },
  { term: 'Sharp power', definition: "Pouvoir de manipulation/desinformation pour influencer des opinions etrangeres (Nye)." },
  { term: 'Crise (Gramsci)', definition: "Quand l'ancien monde meurt et que le nouveau tarde a paraitre." },
  { term: 'Guerre economique (Ali Laidi)', definition: "Strategie economique agressive d'un Etat/entreprise visant des parts de marche ou la puissance." },
  { term: 'Unipolaire', definition: "Systeme international domine par un seul centre." },
  { term: 'Ordre westphalien', definition: "Relations entre Etats souverains aux frontieres lineaires; principe de non-ingerence (1648)." },
  { term: 'Unilatéralisme', definition: "Decision de la puissance dominante selon son seul interet." },
  { term: 'Polylatéralisme', definition: "Gouvernance associant Etats, ONG, FTN et institutions internationales." },
  { term: 'Protectionnisme', definition: "Mesures pour proteger un marche (tarifaires ou non)." },
  { term: 'Capitalisme', definition: "Regime fonde sur le profit, la propriete privee et la libre circulation des biens/services." },
  { term: 'Libre-echange', definition: "Liberalisation des echanges par la reduction/suppression des barrieres douanieres." },
  { term: 'Globalisation financiere', definition: "Marche planetaire des devises et capitaux." },
  { term: 'Liberalisme', definition: "Doctrine politique (limitation des pouvoirs de l'Etat, primat des libertes) et doctrine economique (non-intervention, libre-echange)." },
  { term: 'Choc des civilisations (S. Huntington, 1996)', definition: "Vision des relations internationales structurees par 8 grandes civilisations; these tres controversee." },
  { term: 'Consensus de Washington (1989)', definition: "Paquet de reformes (BM/FMI/FED) promouvant la liberalisation dans les PED via PAS; tres conteste." },
  { term: 'Malthusianisme', definition: "Theorie pronant la limitation des naissances face au risque de surpopulation (T. Malthus)." },
  { term: 'Maritimisation de l economie', definition: "Integration croissante de la voie maritime dans les echanges (conteneurisation, facades dynamiques)." },
  { term: 'Metropolisation', definition: "Concentration des hommes et des fonctions superieures dans de grandes metropoles attractives." },
  { term: 'FTN (Carroue)', definition: "Entreprise capable d'organiser des activites complexes a l'echelle multinationale." },
  { term: 'GAFA / GAFAM', definition: "Grands acteurs du numerique bouleversant l'economie mondiale." },
  { term: 'Etat-nation', definition: "Institutions + peuple + territoire aux frontieres reconnues." },
  { term: 'Souverainete', definition: "Pouvoir supreme de l'Etat (interne/externe), limite par le droit international." },
  { term: 'Populisme', definition: "Critique des elites portee par un leader charismatique; solutions simples a problemes complexes." },
  { term: 'Etat failli', definition: "Incapacite d'assurer les fonctions regaliennes (controle du territoire/population)." },
  { term: 'Guerre (Clausewitz, 1831)', definition: "Acte de violence destine a contraindre l'adversaire; continuation de la politique par d'autres moyens." },
  { term: 'Zone grise', definition: "Espace partiellement hors controle des autorites centrales." },
  { term: 'Pic petrolier (peak oil)', definition: "Moment ou la production mondiale de petrole entame son declin." },
  { term: 'Land grabbing', definition: "Accaparement foncier par des Etats/acteurs etrangers via baux de longue duree." },
  { term: 'Basculement du monde', definition: "Reequilibrage des puissances (re-emergence Russie, eveil Chine, BRICS, ralentissement Nord)." },
  { term: 'Democratie', definition: "Separation des pouvoirs exerces par des representants elus au suffrage universel." },
  { term: 'Puissance (R. Aron)', definition: "Capacite d'une unite politique d'imposer sa volonte aux autres." },
  { term: 'Puissance (H. Morgenthau)', definition: "Cinq piliers: poids geographique, geopolitique, rayonnement culturel, economie, mobilisation autour de valeurs." },
  { term: 'Geopolitique (Y. Lacoste)', definition: "Etude des interactions entre politique et territoire; rivalites et tensions spatiales." },
  { term: 'Capitalisme (Schumpeter)', definition: "Processus de destruction creatrice transformant en permanence la structure economique." },
  { term: 'Premiere mondialisation (S. Berger)', definition: "1870-1914: internationalisation commerce/capitaux au niveau retrouve seulement vers les annees 1980." },
  { term: 'Multipolaire', definition: "Systeme international regi par plusieurs centres de puissance." },
  { term: 'Polycentrisme (M. Foucher)', definition: "Systeme d'influences autour de centres tres inegaux." },
  { term: 'Bipolaire', definition: "Systeme international domine par deux poles." },
  { term: 'Apolaire', definition: "Systeme sans centre dominant clairement organise." },
  { term: 'Multilateralisme', definition: "Gouvernance fondee sur l'egalite de droit entre Etats et adoption de regles concertees." },
  { term: 'Isolationnisme', definition: "Repli sur soi d'un Etat, priorite aux affaires internes; souvent couple au protectionnisme." },
  { term: 'Theorie de la dependance (70s)', definition: "Sous-developpement comme consequence de rapports asymetriques Nord-Sud." },
  { term: 'Developpement durable (Rapport Brundtland, 1987)', definition: "Repondre aux besoins presents sans compromettre ceux des generations futures (3 piliers)." },
  { term: 'Nationalisme', definition: "Ideologie exaltant ou revendiquant la nation; quete d'un Etat pour une communaute (Jaffrelot)." },
  { term: 'Gentrification', definition: "Remplacement de populations modestes par plus aisees dans les centres urbains." },
  { term: 'Paradis fiscal', definition: "Faible fiscalite, secret bancaire, faible regulation: attractif pour capitaux." },
  { term: 'Fonds souverain', definition: "Fonds d'investissement public destine a placer les ressources financieres d'un Etat." },
  { term: 'Croissance de Rostow', definition: "Cinq etapes: societe traditionnelle, prealables, decollage, maturite, consommation de masse." },
  { term: 'Ville mondiale', definition: "Ville concentrant les fonctions de commandement superieures." },
  { term: 'Megalopole', definition: "Continuum urbain de tres grande taille." },
  { term: 'Jour du depassement', definition: "Date a partir de laquelle l'humanite a consomme toutes les ressources que la Terre peut regenerer en un an." },
];

export const REFERENCES: Reference[] = [
  { theme: 'General', refs: ["T. Gomart, L'Affolement du Monde (2019)"] },
  { theme: '1A historique', refs: ["Pierre Hassner, La revanche des passions (2004)", "Laurent Carroue, L'Atlas de la Mondialisation (2020)", "Raymond Aron, Paix et guerre entre les nations (1962)", "Eric Hobsbawm, L'age des extremes (1994)", "J. M. Keynes, Les consequences economiques de la paix (1919)"] },
  { theme: 'Commerce', refs: ["Montesquieu, L'Esprit des Lois (1748)", "Kenichi Ohmae, The Borderless World (1990)", "Suzanne Berger, Made in Monde (2006)", "Adam Smith, Richesse des nations (1776)", "Michael Porter, Competition in Global Industries (1986)"] },
  { theme: 'Frontieres, nationalisme et migrations', refs: ["Branko Milanovic, Global Inequality (2016)", "Regis Debray, Eloge des frontieres (2010)", "Catherine Wihtol de Wenden, Atlas des migrations (2021)", "Michel Foucher, L'obsession des frontieres (2012)"] },
  { theme: 'Mondialisation', refs: ["Dambisa Moyo, L'Aide fatale (2009)", "Daniel Cohen, La mondialisation et ses ennemis (2004)", "Marshall McLuhan, The Medium is the Massage (1967)", "Theodore Levitt, Globalization of Markets (1983)"] },
  { theme: 'Mer et thalassocratie', refs: ["Alfred Mahan, The Influence of Sea Power upon History (1890)", "Halford John Mackinder, The Geographical Pivot of History (1904)", "Nicholas Spykman, America's Strategy in World Politics (1942)", "Pierre Royer, Geopolitique des mers et des oceans (2012)"] },
  { theme: 'Puissance et declin', refs: ["Joseph Nye, The Future of Power (2011)", "Joseph Nye, Bound to Lead (1989)", "Bertrand Badie, Le retournement du monde (1992)", "Bertrand Badie, L'impuissance de la puissance (2004)", "Edward Luttwak, Le reve americain en danger (1993)", "Fareed Zakaria, The Post-American World (2008)", "Zbigniew Brzezinski, Le Grand Echiquier (1997)"] },
  { theme: 'Guerre economique', refs: ["Bernard Esambert, La guerre economique mondiale (1991)", "Edward Luttwak, From Geopolitics to Geoeconomics (1990)", "Ali Laidi, Le droit, nouvelle arme de guerre economique (2019)"] },
  { theme: 'Geographie et villes', refs: ["Saskia Sassen, La Ville globale (1991)", "Bertrand Badie, La fin des territoires (1995)", "Olivier Dollfus, La Mondialisation (1996)"] },
  { theme: 'Realisme', refs: ["Hans Morgenthau, Theory of International Relations (1951)", "J. Herz, Political Realism and Political Idealism (1951)", "S. Walt, The Origins of Alliances (1987)"] },
  { theme: 'Climat et durabilite', refs: ["Hans Jonas, Le Principe responsabilite (1979)", "Sylvie Brunel, Le Developpement Durable (2004)", "Amartya Sen, Repenser l'inegalite (1992)", "Rapport Brundtland (ONU, 1987)", "Rapport Meadows - Halte a la croissance (1972)"] },
  { theme: 'Afrique', refs: ["Sylvie Brunel, L'Afrique. Un continent en reserve de developpement (2004)", "The Economist, Africa Rising (2011)", "The Economist, The New Scramble for Africa (2019)", "Rene Dumont, L'Afrique noire est mal partie (1962)", "Jean-Francois Bayart, L'Etat en Afrique (1989)", "Daron Acemoglu & James Robinson, Why Nations Fail (2012)"] },
  { theme: 'Moyen-Orient', refs: ["Bertrand Badie & Dominique Vidal, Le Moyen-Orient et le monde (2021)", "Olivier Roy, L'Islam mondialise (2004)", "Henry Laurens, Paix et guerre au Moyen-Orient (2005)", "Theodor Herzl, Der Judenstaat (1896)"] },
  { theme: 'Ordre mondial', refs: ["Samuel Huntington, Le choc des civilisations (1996)", "Francis Fukuyama, La Fin de l'histoire (1989)", "Graham Allison, Vers la guerre - Piege de Thucydide (2019)", "Zbigniew Brzezinski, Le Grand Echiquier (1997)", "Dominique Moisi, La geopolitique de l'emotion (2023)", "Richard Haass, A World in Disarray (2017)"] },
  { theme: 'Asie', refs: ["Christophe Jaffrelot, L'Inde de Modi (2019)", "Alain Peyrefitte, Quand la Chine s'eveillera (1973)", "Zhao Tingyang, Tianxia (2016)", "Kaname Akamatsu, Theorie du vol des oies sauvages (1937)"] },
  { theme: 'Amerique du Sud', refs: ["The Economist, Nobody's Backyard - The Rise of Latin America (2010)", "Raul Prebisch, Les USA et le sous-developpement en Amerique latine (1970)"] },
  { theme: 'France', refs: ["Pascal Boniface, La France est-elle encore une grande puissance? (1999)", "Christophe Guilluy, Fractures francaises (2010)", "Jean-Francois Gravier, Paris et le desert francais (1947)", "Maxime Lefebvre, La politique etrangere de la France (2022)"] },
  { theme: 'Europe', refs: ["Francois Heisbourg, Le Temps des Predateurs (2020)", "Pierre Rosanvallon, Le siecle du populisme (2020)", "Guy Verhofstadt, Le Mal Europeen (2016)", "Yves Lacoste, Geopolitique de la Mediterranee (2009)", "Robert Kagan, La Puissance et la Faiblesse (2003)", "Kant, Zum ewigen Frieden (1795)"] },
  { theme: 'Developpement', refs: ["Daron Acemoglu & James Robinson, Why Nations Fail (2012)", "Paul Collier, The Bottom Billion (2008)", "Walt Rostow, Les etapes de la croissance economique (1960)", "Frantz Fanon, Les damnes de la terre (1961)", "Jean Fourastie, Les Trente Glorieuses (1979)"] },
  { theme: 'Demographie', refs: ["Thomas Malthus, Essai sur le principe de la population (1798)", "Paul Ehrlich, La Bombe P (1968)", "Darrell Bricker, Empty Planet (2013)"] },
];

export const SUBJECTS: string[] = [
  "L'Afrique dans la mondialisation depuis 1990",
  "Les ressources naturelles en Afrique : atout ou malediction ?",
  "La Chine en Afrique : nouvelle colonisation ou partenariat gagnant-gagnant ?",
  "Les defis demographiques de l'Afrique",
  "L'integration regionale en Afrique",
  "La Chine, une superpuissance en devenir ?",
  "Les tensions en mer de Chine meridionale",
  "L'Inde dans la mondialisation",
  "Le Japon face au declin demographique",
  "L'ASEAN : vers une integration regionale ?",
  "L'Union europeenne : puissance ou impuissance ?",
  "Le Brexit : causes et consequences geopolitiques",
  "L'elargissement de l'OTAN depuis 1990",
  "L'Allemagne, leader de l'Europe ?",
  "Les Etats-Unis, gendarme du monde ?",
  "Le declin de l'hegemonie americaine",
  "L'integration regionale en Amerique latine",
  "Le Bresil, geant aux pieds d'argile ?",
  "Le Moyen-Orient, un espace de conflits",
  "L'eau au Moyen-Orient : enjeu geopolitique majeur",
  "L'Iran, puissance regionale contestee",
  "Le conflit israelo-palestinien : impasse geopolitique ?",
  "Les printemps arabes : echec ou transformation ?",
  "La Russie, une puissance revisionniste ?",
  "L'energie, arme geopolitique de la Russie",
  "La France, une puissance moyenne a vocation mondiale",
  "La francophonie, outil de puissance francais",
  "La puissance economique suffit-elle a faire une grande puissance ?",
  "Le hard power et le soft power sont-ils complementaires ?",
  "Les nouvelles formes de puissance au XXIe siecle",
  "La transition energetique, nouveau grand jeu geopolitique",
  "Le changement climatique, multiplicateur de menaces",
  "La geopolitique de l'eau",
  "Les migrations internationales : defi ou opportunite ?",
  "La demondialisation est-elle ineluctable ?",
  "Les firmes transnationales, acteurs de la mondialisation",
  "Les frontieres sont-elles encore pertinentes au XXIe siecle ?",
  "La mer, nouvel espace de conflictualite",
  "L'Arctique, nouveau terrain de confrontation",
  "Les guerres du XXIe siecle ont-elles change de nature ?",
  "Le terrorisme international menace-t-il l'ordre mondial ?",
  "Les armes nucleaires garantissent-elles la paix ?",
];

export const HOOKS: HookExample[] = [
  { subject: "L'Afrique dans la mondialisation depuis 1990", hook: "The Economist titrait en 2013 'The New Scramble for Africa', faisant echo au partage colonial du continent a la fin du XIXe siecle.", type: 'actualite' },
  { subject: "Les ressources naturelles en Afrique", hook: "Le Nigeria, premier producteur de petrole d'Afrique, compte 70% de sa population sous le seuil de pauvrete. Cette contradiction illustre le 'resource curse' theorise par Richard Auty.", type: 'paradoxe' },
  { subject: "La Chine en Afrique", hook: "'Quand la Chine construit des routes en Afrique, l'Occident construit des lecons', declarait le president kenyan Uhuru Kenyatta en 2018.", type: 'citation' },
  { subject: "La Chine, une superpuissance en devenir ?", hook: "En 1978, Deng Xiaoping affirmait: 'Peu importe qu'un chat soit blanc ou noir, pourvu qu'il attrape les souris'.", type: 'citation' },
  { subject: "Les tensions en mer de Chine meridionale", hook: "Six Etats revendiquent tout ou partie de la mer de Chine meridionale, espace de 3,5 millions de km2 par lequel transite un tiers du commerce maritime mondial.", type: 'geographique' },
  { subject: "L'Union europeenne : puissance ou impuissance ?", hook: "L'ancien ministre belge Mark Eyskens qualifiait l'UE de 'geant economique, nain politique et ver de terre militaire'.", type: 'citation' },
  { subject: "Le Brexit", hook: "Le 23 juin 2016, 52% des Britanniques votaient pour quitter l'Union europeenne, provoquant le choc politique le plus violent dans l'histoire de la construction europeenne.", type: 'actualite' },
  { subject: "Les Etats-Unis, gendarme du monde ?", hook: "Les Etats-Unis maintiennent 750 bases militaires dans 80 pays, depensent plus de 800 milliards de dollars par an en defense.", type: 'chiffre' },
  { subject: "Le declin de l'hegemonie americaine", hook: "En 1945, les Etats-Unis representaient 50% du PIB mondial. En 2024, cette part est tombee a 25%.", type: 'chiffre' },
  { subject: "Le Moyen-Orient, un espace de conflits", hook: "Yemen, Syrie, Irak, Libye, Palestine... Aucune autre region au monde ne concentre autant de conflits actifs.", type: 'paradoxe' },
  { subject: "L'eau au Moyen-Orient", hook: "Avec moins de 1000 m3 d'eau douce par habitant et par an, le Moyen-Orient est la region la plus aride du monde.", type: 'chiffre' },
  { subject: "La Russie, une puissance revisionniste ?", hook: "'La Russie n'a pas de frontieres, elle n'a que des horizons', affirmait le ministre Sergue Lavrov.", type: 'citation' },
  { subject: "L'energie, arme geopolitique de la Russie", hook: "La Russie fournissait avant 2022 40% du gaz naturel consomme en Europe.", type: 'chiffre' },
  { subject: "La France, puissance moyenne a vocation mondiale", hook: "Avec 13 millions de km2 de zone economique exclusive repartis sur tous les oceans, la France possede le deuxieme domaine maritime mondial.", type: 'geographique' },
  { subject: "La transition energetique", hook: "La production d'une voiture electrique necessite 6 fois plus de mineraux que celle d'un vehicule thermique.", type: 'chiffre' },
  { subject: "Le changement climatique, multiplicateur de menaces", hook: "Le Pentagone qualifie le changement climatique de 'threat multiplier', multipliant les risques de conflits pour l'acces aux ressources.", type: 'citation' },
  { subject: "La geopolitique de l'eau", hook: "Le barrage Renaissance sur le Nil Bleu, construit par l'Ethiopie, retient 74 milliards de m3 d'eau, menacant l'Egypte et le Soudan.", type: 'actualite' },
  { subject: "Les migrations internationales", hook: "272 millions de personnes vivaient hors de leur pays de naissance en 2019, soit 3,5% de la population mondiale.", type: 'chiffre' },
  { subject: "La demondialisation est-elle ineluctable ?", hook: "Le commerce international, qui representait 61% du PIB mondial en 2008, n'en represente plus que 57% en 2023.", type: 'chiffre' },
  { subject: "Les frontieres sont-elles encore pertinentes ?", hook: "Regis Debray affirmait en 2010: 'L'eloge des frontieres est devenu aussi incongru que pouvait l'etre leur critique il y a trente ans'.", type: 'citation' },
  { subject: "La mer, nouvel espace de conflictualite", hook: "90% du commerce mondial transite par voie maritime, 30% de la production petroliere est offshore et 95% des communications numeriques passent par des cables sous-marins.", type: 'chiffre' },
  { subject: "Le terrorisme international", hook: "Les attentats du 11 septembre 2001 ont declenche une 'guerre contre le terrorisme' qui a coute 8000 milliards de dollars.", type: 'chiffre' },
  { subject: "Le hard power et le soft power", hook: "Joseph Nye theorisait en 1990 le concept de 'soft power'. Mais l'invasion russe de l'Ukraine en 2022 a rappele que le hard power conserve toute sa pertinence.", type: 'citation' },
  { subject: "Le Bresil, geant aux pieds d'argile ?", hook: "'Le Bresil est le pays de l'avenir et le restera toujours', raille l'adage popularise par Stefan Zweig.", type: 'citation' },
  { subject: "Le conflit israelo-palestinien", hook: "Depuis les Accords d'Oslo de 1993, la colonisation israelienne en Cisjordanie a triple, passant de 250 000 a 700 000 colons.", type: 'chiffre' },
];
